# PA 2: Classification - Decision Tree

## Student Details
Student Name and ID:Eshan Danayakapura Jagadeesh Id : 1001667159___


Notes: When submitting, fill your name and ID in this cell.  [1 point]


Do not to forget to cite any external sources used by you.

## Programming Assignment Submission Instructions


Step 1: Rename this submission file as 'yourLastName_Last4digitsofyourID_DT.ipynb' [1 point]

Step 2: Place this file inside the folder 'PA#2_Classification_yourLastName_Option1'  [1 point]


## Programming Assignment Details

This is an individual assignment. 

For this assignment use Jupyter notebook, Panda, and scikit.

- Load wine dataset from sklearn datasets.  [2 points]
- Create a dataframe and print the first and last five records of your dataset.  [2 points]
- Print the class names.  [2 points]
- Split your dataset 70% for training, and 30% for testing the classifier.  [2 points]
- Use gini and entropy to measure the quality of a split.  [5 points]
- Use comments to explain your code and variable names. [2 points]
- Calculate and print the confusion matrix, and the classification Report (includes: precision, recall, f1-score, and support).  [5 points]
- Print the decision tree visualization.  [5 points]

## Report

For each classification task you need to submit a report (Microsoft Word, or PDF) that you have to:
- describe the Decision Tree method,  [5 points]
- the dataset and if you have done any pre-process, and [5 points]
- your code. [2 points]
- Visualization of the decision tree for gini and entropy.[8 points]
- Interpret your results, and do not forget to compare gini and entropy [10 points]

Do not to forget to cite your sources!


Step 3: Save your report file as 'yourLastName_Last4digitsofyourID_DT.doc'  [1 point]

Step 4: Place this file inside the folder 'PA#2_Classification_yourLastName_Option1'  [1 point]

# - - - - - - - - - - - - - - - Solution - - - - - - - - - - - - - - - - - - 

In [1]:
#Importing all required classes
from sklearn.datasets import load_wine
from sklearn import tree 
from sklearn import datasets
import graphviz
import pandas as pd
from graphviz import Graph
import numpy as np


In [2]:
#Loading wine dataset from sklearn datasets and creating a dataframe
wine = load_wine()
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
col_names = ['label','col 1','col 2','col 3','col 4','col 5','col 6','col 7','col 8','col 9','col 10','col 11','col 12','col 13']
winee = pd.read_csv(url,header = None, names = col_names)
wine1 = datasets.load_wine()
data1 = pd.DataFrame(data= np.c_[wine1['data'], wine1['target']],
                     columns= wine1['feature_names'] + ['target'])


In [5]:
#displaying the first five rows of data
data1.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0     0.0  
1                          3.40   1050.0     0.0  
2                          3.17   1185.0     0.0  
3                          3.45   1480.0     0.0  
4                          2.93    735.0     0.0

In [6]:
##Printing the last five records of your dataset
data1.tail()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
173        0.61                  0.52             1.06              7.7  0.64   
174        0.75                  0.43             1.41              7.3  0.70   
175        0.69                  0.43             1.35             10.2  0.59   
176        0.68                  0.53             1.46              9.3  0.60   
177        0.76                  0.56             1.35              9.2  0.61   

     od280/od315_of_diluted_wines  proline  target  
173                          1.74    740.0     2.0  
174                          1.56    750.0     2.0  
175                          1.56    835.0     2.0  
176                          1.62    840.0     2.0  
177                          1.60    560.0     2.0

In [7]:
#Printing the class names
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [8]:
# defining X and y for future computations
feature_cols = ['label','col 1','col 2','col 3','col 4','col 5','col 6','col 7','col 8','col 9','col 10','col 11','col 12','col 13']
X = winee[feature_cols]
y = winee.label

In [9]:
# Splitting the dataset into 70% for training, and 30% for testing the classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=0)



In [10]:
#Using gini to measure the quality of the split
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100) 
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [11]:
##Using entropy to measure the quality of the split
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [12]:
from sklearn.metrics import accuracy_score 
y_pred = clf_gini.predict(X_test) 
y_pred
y_pred_en = clf_entropy.predict(X_test) 
y_pred_en

print ("Accuracy is ", accuracy_score(y_test,y_pred)*100)
print ("Accuracy is ", accuracy_score(y_test,y_pred_en)*100)

Accuracy is  100.0
Accuracy is  100.0


In [13]:
#Calculating the Confusion Matrix
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred_class = logreg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred_class))

[[19  0  0]
 [ 0 21  1]
 [ 0  0 13]]


In [14]:
# Computing and printing the confusion matrix, and the classification Report (includes: precision, recall, f1-score, and support)
confusion = metrics.confusion_matrix(y_test, y_pred_class)
a = confusion[0,0]
b = confusion[0,1]
c = confusion[0,2]
d = confusion[1,0]
e = confusion[1,1]
f = confusion[1,2]
g = confusion[2,0]
h = confusion[2,1]
i = confusion[2,2]
precision1 = (a)/(a+b+c)
precision2 = (e)/(d+e+f)
precision3 = (i)/(g+h+i)
recal1 = (a)/(a+d+g)
recal2 = (e)/(b+e+h)
recal3 = (i)/(c+f+i)
f11 = (2*precision1*recal1)/(precision1+recal1)
f12 = (2*precision2*recal2)/(precision2+recal2)
f13 = (2*precision3*recal3)/(precision3+recal3)
print(precision1)
print(precision2)
print(precision3)
print(recal1)
print(recal2)
print(recal3)
print(f11)
print(f12)
print(f13)

1.0
0.9545454545454546
1.0
1.0
1.0
0.9285714285714286
1.0
0.9767441860465117
0.962962962962963


In [15]:
#Printing the decision tree visualization.
clf = tree.DecisionTreeClassifier()
 
clf = clf.fit(wine.data, wine.target) 
tree.export_graphviz(clf, out_file='tree.dot')